language: python
dist: xenial
cache:
    pip: true
    directories:
        - /usr/local/bin
        - /usr/local/lib/python$TRAVIS_PYTHON_VERSION/site-packages
python:
    - '3.7'
install:
    - pip install pipenv
    - python3 setup.py install
    - pipenv install --dev --system
script:
    - flake8 --verbose apertium
    - mypy apertium --strict --any-exprs-report .mypy_coverage --ignore-missing-imports;
      cat .mypy_coverage/any-exprs.txt;
      coverage=$(tail -1 .mypy_coverage/any-exprs.txt | grep -Eo '[0-9\.]+%' | sed 's/%$//');
      if (( $(echo "$coverage < 95" | bc -l) )); then
          exit 1;
      fi;
    - coverage run -m unittest --verbose --buffer tests
    - coverage report --show-missing --fail-under 90 --include 'apertium/**'
    - cat ./tests/kaz.txt | tee /dev/fd/2 | apertium kaz-tat
    - lt-proc -w /usr/share/apertium/apertium-kaz-tat/kaz-tat.automorf.bin ./tests/kaz.txt
after_success:
    - coveralls
notifications:
    on_failure: change
    on_success: change
matrix:
    allow_failures:
        - python: nightly
